baseURL = 'https://fejix.dev'
languageCode = 'en-us'
title = 'Fejix website'
theme = 'bootstrap'


# Output directory
publishDir = 'generated_website'

enableEmoji = true

# Bootstrap theme docs: https://hbs.razonyang.com/en/docs/configuration/