# Menu

[[main]]
name = 'Home'
identifier = 'menu-home'
url = '/'
weight = 1

[[main]]
name = 'Blog'
identifier = 'menu-blog'
url = '/blog'
weight = 2

[[main]]
name = 'Tutorials'
identifier = 'menu-tutorial'
url = '/tutorials'
weight = 3

[[main]]
name = 'Docs'
identifier = 'menu-docs'
url = '/docs'
weight = 4