[book]
title = "FjML Tutorial"
authors = ["MarkLagodych"]
description = "Fejix Markup Language tutorial and Fejix basics explanations"
src = "src"
language = "en"
multilingual = false

[output.html]
git-repository-url = "https://github.com/FejixGUI/Fejix-website/tree/main/books/fjml-tutorial"
additional-js = ["fjml.min.js"]

[output.html.fold]
enable = true